<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sec-view_PasswordOne upper letter required-_99eb12</name>
   <tag></tag>
   <elementGuidId>4bb4a31a-2c85-4ca2-9cf9-7c8c873c0266</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='formCover']/div/div[2]/sec-view</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>sec-view</value>
      <webElementGuid>dd974014-9cf7-4c50-8a1d-303fba114873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-name</name>
      <type>Main</type>
      <value>userPassword</value>
      <webElementGuid>4bffcdbf-1be1-402a-a7af-51a178de7722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>a-hint</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>4fc69292-7bf9-4e7c-95b6-b83a7a452532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>a-hint-description</name>
      <type>Main</type>
      <value>RegisterPage</value>
      <webElementGuid>4e05f3a4-d87d-48f7-81d3-241befad9498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>a-type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ea3295d9-3a37-4c29-be1a-854edf89353a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-model</name>
      <type>Main</type>
      <value>model.password</value>
      <webElementGuid>fba6b1a9-5a8b-49dc-8b1b-5403aa2adbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-require</name>
      <type>Main</type>
      <value>mainCtrl.getRequire('Password')</value>
      <webElementGuid>54604bf0-2205-4a53-8747-05f7992397e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-min-length</name>
      <type>Main</type>
      <value>mainCtrl.getMin(4)</value>
      <webElementGuid>5bf9ef11-bda9-464a-aa25-0a5ecd19d4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-max-length</name>
      <type>Main</type>
      <value>mainCtrl.getMax(12)</value>
      <webElementGuid>9708eca1-8491-4d80-8b85-ae11a8e8ef56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-pattern</name>
      <type>Main</type>
      <value>mainCtrl.getPattern('Password')</value>
      <webElementGuid>1b2c747b-b5db-4ab8-b46e-997fcb54362e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-isolate-scope sec-view</value>
      <webElementGuid>c65a5137-5f9c-40f6-b2ea-eed518fc20fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                *PasswordOne upper letter required- Use  4 character or longer - Use maximum 12 character - Including at least one lower letter - Including at least one upper letter - Including at least one number </value>
      <webElementGuid>647f3256-ad14-4adb-bc03-070196ad7360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formCover&quot;)/div[1]/div[@class=&quot;spliter&quot;]/sec-view[@class=&quot;ng-isolate-scope sec-view&quot;]</value>
      <webElementGuid>b69513d4-fe6a-40b1-8cde-e00c1640b16c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formCover']/div/div[2]/sec-view</value>
      <webElementGuid>1a142458-68e8-4b6d-afff-63321a4e988d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::sec-view[1]</value>
      <webElementGuid>b7e88093-90cd-4f9a-8f3c-04e1b4315a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/sec-view</value>
      <webElementGuid>d23ba4bb-3a55-470e-967f-1b6077959136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//sec-view[(text() = '
                                *PasswordOne upper letter required- Use  4 character or longer - Use maximum 12 character - Including at least one lower letter - Including at least one upper letter - Including at least one number ' or . = '
                                *PasswordOne upper letter required- Use  4 character or longer - Use maximum 12 character - Including at least one lower letter - Including at least one upper letter - Including at least one number ')]</value>
      <webElementGuid>5cf01d0d-040c-4730-bec3-10442b81aed9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
