<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cityInput</name>
   <tag></tag>
   <elementGuidId>271c227e-4a9d-4e17-8c77-9ab2c62142ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cityRegisterPage&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cityRegisterPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c077d652-4ebd-4e2f-b5cf-7c9ed0ea4d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cityRegisterPage</value>
      <webElementGuid>4a866c3e-ace2-438a-b02e-5fac334aa852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7f9d2b04-c68f-4813-addc-17e864e5a36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>secModel</value>
      <webElementGuid>7f75eede-1f60-4567-ba46-272e16fbed58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-scope in-focus</value>
      <webElementGuid>f7f52931-8d7c-4638-aa5a-7cdbf5072383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formCover&quot;)/div[3]/div[@class=&quot;spliter&quot;]/sec-view[@class=&quot;ng-isolate-scope sec-view&quot;]/div[@class=&quot;inputContainer ng-scope&quot;]/input[@class=&quot;ng-pristine ng-untouched ng-valid ng-scope in-focus&quot;]</value>
      <webElementGuid>317d9b8b-3063-46e9-ba1e-259bfca5a5bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cityRegisterPage']</value>
      <webElementGuid>52affabd-0288-446b-8729-530190a752d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formCover']/div[3]/div/sec-view[2]/div/input</value>
      <webElementGuid>5728e358-8345-42d8-8892-2ab4660baa96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/sec-view[2]/div/input</value>
      <webElementGuid>3749dcd3-c1a1-4274-9157-22f5cbbe7e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cityRegisterPage' and @type = 'text']</value>
      <webElementGuid>589883ad-03f4-4f5b-8d2a-2487f8242a5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
